baseURL = "https://www.oslabenaimunita.cz"
disqusShortname = ""
googleAnalytics = ""
languageCode = "cs-CZ"
languageName = "CZ"
paginate = "6"
summaryLength = "15"
theme = "bigspring"
title = "Oslabená imunita"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
URL = "#"
name = "About Us"
weight = 3
[[menu.footer_left]]
URL = "pricing"
name = "Pricing"
weight = 1
[[menu.footer_left]]
URL = "#"
name = "Quick Start"
weight = 2
[[menu.footer_middle]]
URL = "#"
name = "Features"
weight = 1
[[menu.footer_middle]]
URL = "#"
name = "Platform"
weight = 2
[[menu.footer_middle]]
URL = "pricing"
name = "Pricing"
weight = 3
[[menu.footer_right]]
URL = "faq"
name = "FAQ"
weight = 1
[[menu.footer_right]]
URL = "terms-conditions"
name = "Terms & Conditions"
weight = 2
[[menu.footer_right]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "Oslabenaimunita.cz | zákaz kopírování textů, všechna práva vyhrazena"
description = "Znáte svůj imunitní systém a víte, jak jej podpořit?"
footer_content = "Jak funguje váš imunitní systém? A jak ho můžete podpořit? Odpověď se dozvíte na našem webu."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
logo = "images/logo-oslabena-imunita.png"
logo_width = "200px"
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-skype"
link = "#"
title = "skype"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
